# Copyright © KhulnaSoft Dev <info@khulnasoft.com>
#
# SPDX-License-Identifier: CC0-1.0
#
# This file is maintained in https://github.com/deepSquads/meta/
#
extends: default

rules:
  line-length:
    max: 500
    level: error
  document-start: disable
  indentation:
    indent-sequences: false
