#!/bin/sh

# Copyright © KhulnaSoft Dev <info@khulnasoft.com>
#
# SPDX-License-Identifier: CC0-1.0

#git grep -l 'Copyright .*[0-9][ –-]\+\(201[0-9]\|202[0123]\) KhulnaSoft Dev' | grep -v '\.po$' | xargs -r sed -i 's/\(Copyright [^0-9]*\)\([0-9]\+[ –-]\+[0-9]\+\) \(KhulnaSoft Dev\) <michal@[^>]\+>/\1\3 <info@khulnasoft.com>/'

#sed -i s@https://github.com/charliermarsh/ruff-pre-commit@https://github.com/astral-sh/ruff-pre-commit@ .pre-commit-config.yaml

sed -i s%codecov/codecov-action@v3%codecov/codecov-action@v4% .github/workflows/*

for file in .github/workflows/*.yml ; do
    "${ROOT:-.}/update-workflow" "$file"
done

"${ROOT:-.}/update-pre-commit" .pre-commit-config.yaml

if [ -f pyproject.toml ] ; then
    sed -i 's@^format = "github"@output-format = "github"@' pyproject.toml
    pre-commit run --files pyproject.toml || true
fi
