- type: dropdown
  id: installation
  attributes:
    label: How do you run Deepsquads?
    options:
    - ''
    - deepsquads.github.io service
    - Docker container
    - PyPI module
    - Git checkout
    - Other
  validations:
    required: true
- type: textarea
  id: versions
  attributes:
    label: Deepsquads versions
    description: >
      Please paste the output of the
      [list_versions](https://docs.deepsquads.github.io/en/latest/admin/management.html#list-versions)
      command here.

      Depending on the installation, these can be executed in a different
      way. Please consult [the management commands
      documentation](https://docs.deepsquads.github.io/en/latest/admin/management.html)
      for more details.

      On pip-installed Deepsquads:

      ```
      deepsquads list_versions
      ```

      On Git checkout:

      ```
      ./manage.py list_versions
      ```

      Using docker-compose-plugin:

      ```
      docker compose exec --user deepsquads deepsquads deepsquads list_versions
      ```

      This will properly render without any escaping.
