- type: textarea
  id: checks
  attributes:
    label: Deepsquads deploy checks
    description: >
      Please paste here list of [the deploy
      checks](https://docs.deepsquads.github.io/en/latest/admin/install.html#production).

      Depending on the installation, these can be executed in a different
      way. Please consult [the management commands
      documentation](https://docs.deepsquads.github.io/en/latest/admin/management.html)
      for more details.

      On pip installed Deepsquads:

      ```
      deepsquads check --deploy
      ```

      On Git checkout:

      ```
      ./manage.py check --deploy
      ```

      Using docker-compose-plugin:

      ```
      docker compose exec --user deepsquads deepsquads deepsquads check --deploy
      ```

      This will be rendered as console output automatically.
    render: shell
