# Copyright © KhulnaSoft Dev <info@khulnasoft.com>
#
# SPDX-License-Identifier: CC0-1.0

# This file is maintained in https://github.com/deepSquads/meta/
name: Lint Code Base

on:
  push:
    branches-ignore:
    - deepsource-fix-**
    - renovate/**
    - deepsquads
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Lint Code Base
      uses: github/super-linter/slim@v5.0.0
      env:
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VALIDATE_PYTHON_ISORT: false
        VALIDATE_JSCPD: false
        VALIDATE_GITHUB_ACTIONS: false
        VALIDATE_YAML: false
